### PR TITLE
Post Requests done

### LINKED ISSUE #8: Create Post Requests for All Datatypes
**Description**
Create Post Requests for All Datatypes

**Acceptance Criteria**
- Working Post Requests for Users
- Working Post Requests for Groups
- Working Post Requests for Baskets
- Working Post Requests for Items

**Additional Information**
- Feel free to steal from this [H4I Repo](https://github.com/hack4impact-calpoly/habitat-for-humanity/blob/dev/backend/routes/userRoutes.js)

### PR DESCRIPTION
**Pull request by zmattes04**
## Developer: Zach Mattes

Closes #8 

### Pull Request Summary
  
I added the post requests for groups, baskets, users, and items.
(Sorry the branch is called path_requests and I did Post Requests. I'm aware and will do patch requests in a bit.
I wasnt able to rename it for some reason.)

### Modifications

I modified the schema files and the route files.

### Testing Considerations
I used boomerang to run the post and used get to confirm.
{list out what you have tested and what the reviewer should verify}

### Pull Request Checklist

- [ ] Code is neat, readable, and works
- [ ] Comments are appropriate
- [ ] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [ ] The developer name is specified
- [ ] The summary is completed
- [ ] Assign reviewers

### Screenshots/Screencast
Screenshot 2024-05-10 at 4 55 01 PM

{put screenshots of your change, or even better a screencast displaying the functionality}

### CODE REVIEW

**Comment by zmattes04** [comment]
Screenshot 2024-05-10 at 4 56 58 PM
Screenshot 2024-05-10 at 4 56 38 PM
Screenshot 2024-05-10 at 4 56 14 PM

**Comment by SilveerDusk** [comment]
Looks good to me. @jhagendoornCP Second Reviewer?

**Review by SilveerDusk — APPROVED** [review]
@ZachAttackUS, Groups should have an array of baskets and I believe they currently do.  Expand more on the default description; is that something we need to do in the frontend or can it be done in the backend?

**Comment by zmattes04** [comment]
@SilveerDusk, most likely the default description should be done in frontend? I was thinking like if left blank it either does no description or just "no description given"

**Comment by jhcsdev** [comment]
i can check this soon, sorry i don't have github notifs on lol

**Review by jhcsdev — APPROVED** [review]
looks good to me, great job zach

**Comment by jhcsdev** [comment]
can we delete this branch?

**Pull request merged**
