### PR TITLE
Basket component

### LINKED ISSUE #31: Create the Table for Basket Component
**User Story**
User story goes here

**Description**

**Acceptance Criteria**

Steps:
- step 1
- step 2

**Additional Information**

### PR DESCRIPTION
**Pull request by jhcsdev**
Closes #31 #67 #23 #66 
### Pull Request Summary

Added the basket component. Renders all items and some info about the basket. DID NOT add the Add Item component (although the button is there) since I believe Zach is working on it. Sorry it took awhile to make the pull request I have been in shambles all day after 7 hours of driving. 

### Modifications

Basket, basketItem, endpoint for baskets, two CSS files

### Testing Considerations

Responsive formatting and rendering at least 1 item / basket correctly. We will need to test that it renders properly for more items though. 

### Screenshots/Screencast

Multiple baskets on the same page 
Screenshot 2024-05-24 at 10 01 24 PM

Basket fails rendering 
Screenshot 2024-05-24 at 10 01 58 PM

Mobile/smaller screens formatting 
Screenshot 2024-05-24 at 10 06 44 PM

### CODE REVIEW

**Comment by jhcsdev** [comment]
forgot to mention that there are other functionality that i couldn't test without logging in because i changed it so that only the user that logs in can see it, there's also some other hidden things that render/derender based off of user state like the "delete from group option" and also none of the buttons have backend functionality because i wanted to get the frontend out first so that other people could use it and also so that suggestions could be made, i wanted to work on this more today i just died and didn't work on it :/

**Comment by sofijadimitrijevic1** [comment]
looks awesomeee we gotta merge now

**Comment by zmattes04** [comment]
is there an add basket button somewhere?
looks good otherwise!

**Comment by jhcsdev** [comment]
@ZachAttackUS add basket will be added on the group page, but baskets have an add item!

**Pull request merged**
