### PR TITLE
Add baskets to individual group page

### LINKED ISSUE #116: Add Baskets to Individual Group Page
**User Story**
User story goes here

**Description**

**Acceptance Criteria**

Steps:

- step 1
- step 2

**Additional Information**

### PR DESCRIPTION
**Pull request by sofijadimitrijevic1**
## Developer: {Full Name}

Closes #116 

### Pull Request Summary

Basket components that are associated with a group now show up on each individual group page

### Modifications

Modified IndividualGroupPage, made fetchBaskets function, added the baskets fetched to the basket placeholder on the page.

### Testing Considerations

Tested that it correctly renders for general cases (zero baskets, one basket, more than one basket) (will need to write actual cypress tests for this)

### Pull Request Checklist

- [ ] Code is neat, readable, and works
- [ ] Comments are appropriate
- [ ] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [ ] The developer name is specified
- [ ] The summary is completed
- [ ] Assign reviewers

### Screenshots/Screencast

{put screenshots of your change, or even better a screencast displaying the functionality}
Screenshot 2024-05-29 at 12 46 06 AM

https://github.com/Gather307/Gather/assets/113939891/1925111a-41f4-4d9b-9995-1d32f644067f

### CODE REVIEW

**Comment by zmattes04** [comment]
looks good can we make it so where it says members it shows username instead of id. i feel like thats a pretty easy fix.

**Comment by SilveerDusk** [comment]
Looks good! @sofijadimitrijevic1 Do the buttons work or is it just frontend rn?

**Comment by sofijadimitrijevic1** [comment]
@SilveerDusk it is just frontend

**Comment by zmattes04** [comment]
can we merge this to main so i can try to add my "add basket button somewhere?

**Pull request merged**
