### PR TITLE
34 create the group page

### LINKED ISSUE #34: Create the Group Page
(each individual group displayed)
**User Story**
User story goes here

**Description**

**Acceptance Criteria**

Steps:
- step 1
- step 2

**Additional Information**

### LINKED ISSUE #69: Create the Group Page
**User Story**
User story goes here

**Description**

**Acceptance Criteria**

Steps:

- step 1
- step 2

**Additional Information**

### PR DESCRIPTION
**Pull request by sofijadimitrijevic1**
## Developer: Sofija Dimitrijevic

Closes #34 

### Pull Request Summary
Finally finished layout for individual group page, with some functionality (displays the group's information when you click on it, back button takes you back to the groups page). Made placeholder for basket component. Still using chakra ui so if we want this to have the same design as the groups page Jonathan imma need you to help me with css :D
### Modifications

Created IndividualGroupPage file

### Testing Considerations

I need to test this more formally still, but just by using it the page works well when clicking on any of our current groups (displays all the correct information). Still need to connect to IUsers as display the usernames of the users in the groups and not just the id's. Works fine when changing screen sizes.

### Pull Request Checklist

- [ ] Code is neat, readable, and works
- [ ] Comments are appropriate
- [ ] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [ ] The developer name is specified
- [ ] The summary is completed
- [ ] Assign reviewers

### Screenshots/Screencast

Screenshot 2024-05-25 at 1 08 10 AM
Screenshot 2024-05-25 at 1 09 09 AM

### CODE REVIEW

**Comment by jhcsdev** [comment]
this looks good! i think we should maybe make a couple of changes - 
1) would it be possible to replace memberIds with usernames and possibly their avatar? 
2) what's the difference between the settings icon displayed right under the navbar and the edit group button? if they do the same thing we can probably remove one 

overall though i really like it! good work

**Review by jhcsdev — CHANGES_REQUESTED** [review]
see above comment

**Comment by sofijadimitrijevic1** [comment]
> this looks good! i think we should maybe make a couple of changes -
> 
> 1. would it be possible to replace memberIds with usernames and possibly their avatar?
> 2. what's the difference between the settings icon displayed right under the navbar and the edit group button? if they do the same thing we can probably remove one
> 
> overall though i really like it! good work

1. Yes that's what I was going to do but Jason was saying there was some issue with users that we need to go over first I'm not sure what it was though, I'm gonna play around with that rn
2. For settings I had no idea what we needed that for it was just on the figma so I added an icon in case you and Zach wanted it for some reason so i'm going to remove it now!

edit: completed both of these changes! I also found a bug, the search bar would cover some of with Go Back when the screen size was the smallest it would go, so now i just stacked the send invite on top of search bar when the screen size gets smaller, it doesn't look amazing but it's good enough for now. i'll merge with main now!

Screenshot 2024-05-25 at 9 42 54 PM
Screenshot 2024-05-25 at 9 43 09 PM

**Review by SilveerDusk — APPROVED** [review]
Looks good!

**Pull request merged**
