### PR TITLE
Profile Page

### LINKED ISSUE #18: Create Profile Page
**User Story**
User story goes here

**Description**

**Acceptance Criteria**

Steps:
- step 1
- step 2

**Additional Information**

### LINKED ISSUE #24: Create the User Info Component
**User Story**
User story goes here

**Description**

**Acceptance Criteria**

Steps:
- step 1
- step 2

**Additional Information**

### PR DESCRIPTION
**Pull request by palldas**
## Developer: Pallavi Das

Closes #18 #24 

### Pull Request Summary

Created the UserProfile Component and Profile Page setup, can copy the user id. can edit the firstname and lastname and will edit in user database (for now can't edit email, password, username). Friendslist component is displayed.

### Modifications

{list out the files created/modified and a brief description of what was changed}

### Testing Considerations

haven't tested yet

### Pull Request Checklist

- [ ] Code is neat, readable, and works
- [ ] Comments are appropriate
- [ ] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [ ] The developer name is specified
- [ ] The summary is completed
- [ ] Assign reviewers

### Screenshots/Screencast
Screen Shot 2024-05-23 at 12 25 42 AM

### CODE REVIEW

**Comment by zmattes04** [comment]
Looks good to me!

**Comment by palldas** [comment]
just did it on this branch but implemented show and hide password on login and signup page
Screen Shot 2024-05-23 at 10 52 41 AM
Screen Shot 2024-05-23 at 10 52 50 AM

**Review by SilveerDusk — APPROVED** [review]

**Comment by sofijadimitrijevic1** [comment]
looks great!

**Comment by jhcsdev** [comment]
Pallavi, this is incredible. I'm so proud of what you've done here. You're going places!

**Comment by SilveerDusk** [comment]
Love the attention to detail, profile page looks great and it looks like it displays the user info properly as well!

**Pull request merged**
