### PR TITLE
E2E test 

### PR DESCRIPTION
**Pull request by jhcsdev**
Added an E2E test which visits all pages / routes

If you're reviewing please pull from this branch and run npm run cyp, click on E2E-testing, and then happyPath.cy.js, and confirm that the test passes on your side!!!! We want to make sure that this works on every computer.

### CODE REVIEW

**Review by jhcsdev — COMMENTED** [review]
Looks great. Great work on this E2E test.

**Comment by sofijadimitrijevic1** [comment]
I just ran it and everything passes, great job Jonathan!!

**Comment by zmattes04** [comment]
honestly you did a great job. Heres your star! Go and put on your bulletin board!

**Review by SilveerDusk — APPROVED** [review]
Passes all test when running locally for me!

**Pull request merged**
