### PR TITLE
Fixes Navbar, Updates User Profile, Fixes Auth Redirect Issue, and Updates Move Item to Work

### PR DESCRIPTION
**Pull request by SilveerDusk**
## Developer: Jason Jelincic

Closes # none

### Pull Request Summary

Fixes Navbar, Updates User Profile, Fixes Auth Redirect Issue, and Updates Move Item to Work

### Modifications

- NavbarSingedIn
- App
- profilepage
- userinfo
- itemspage
- edits
- itemsgroup
- groups page
- individual group page

### Testing Considerations

-cleaned db and ran on localhost

### Pull Request Checklist

- [ ] Code is neat, readable, and works
- [ ] Comments are appropriate
- [ ] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [ ] The developer name is specified
- [ ] The summary is completed
- [ ] Assign reviewers

### Screenshots/Screencast
sent to group chat

### CODE REVIEW

**Comment by SilveerDusk** [comment]
Do we want to change members on groups and baskets to be done by username as it is unique and doesnt require any changes but would provide us with better access of the group members usernames?

**Comment by jhcsdev** [comment]
> Do we want to change members on groups and baskets to be done by username as it is unique and doesnt require any changes but would provide us with better access of the group members usernames?

we should def do this, having member ids on top of usernames is kind of redundant and it's so much easier to add a friend by username too

**Comment by palldas** [comment]
> Do we want to change members on groups and baskets to be done by username as it is unique and doesnt require any changes but would provide us with better access of the group members usernames?

^ i can do this
the updated schema looks good to merge!

**Review by palldas — APPROVED** [review]
looks good, just fix the merge conflicts

**Review by jhcsdev — APPROVED** [review]
looks good not sure what happens if a user doesn't have an associated avatar with it on backend but I'm assuming their avatar will just render either nothing or their username i don't think it'll crash anything

**Comment by SilveerDusk** [comment]
> looks good not sure what happens if a user doesn't have an associated avatar with it on backend but I'm assuming their avatar will just render either nothing or their username i don't think it'll crash anything

@jhagendoornCP the avatar is handled by Charka and it's just a random color and their first letter

**Pull request merged**
