### PR TITLE
My Groups Page

### LINKED ISSUE #16: Create the My Groups Page
**User Story**
As an organizer, I’d like to be able to see all the events I am planning and the items that individuals are bringing when I’m planning events, so that I can keep track of who’s bringing what, how much money each item costs, and keep things equitable. (Jonathan Hagendoorn)

**Description**
Create a groups page that looks similar to the figma. Instead of displaying the groups, add centered text that says "no groups yet" or something like that.
Image

**Acceptance Criteria**
- Groups page looks similar to figma
- Search bar is there but not functional
- Buttons to create groups and invite members are there as in figma but not functional
- Button/Hyperlink to switch to the items page (/items) is there but should take you to a 404 since the items page wont be build yet

Steps:
Feel free to add your own or let me know, but follow the figma for now.

**Additional Information**

### PR DESCRIPTION
**Pull request by jhcsdev**
Jonathan Hagendoorn

Closes #16

### Summary of changes

Created the MyGroupsPage. This involved considerably more UI than I had predicted which made it take a bit longer than it should have. Built some utility components as well, like a skeletongroup, pageselector, and constrained text, and tried to make them as generic as possible for reuse in other changes. 

Since I made a couple CSS files, I also went ahead and refactored index.css and App.css along with my two CSS files into a new "styles" directory to bring all styles to the same place, but if everyone else doesn't like that we can revert it to how it was.

Also, I wrapped the app in a box with 100vw and 100vh because I noticed that the app was not correctly displaying when you passed CSS styles of height=100% (as in, the page was extending a bit over the viewport and adding a scrollbar for no reason). Now behavior should work properly across all pages. I checked that this worked on the available pages and it did.

### Modifications

PageSelector, CompactGroupComponent, All CSS files, SkeletonGroup, SearchBar, ConstrainedText, PageNumberButton, App.tsx. I know that github says I edited 18 files, some of those are edited only because I saved on habit and prettier VSCode extension auto-formatted the file. 

### Testing Considerations

I have tested that different shapes of the grid works and renders correctly, and also that all routing links (routing to specific group on /groups/id endpoint and routing to the items page on /items) correctly redirect page. I also tested different numbers on the page selector, but since I didn't want to inflate the database with false groups I decided to NOT test with more groups, which means I was not able to test that the pageSelector renders correctly when there are more pages than the specified limit (see 

### Screenshots/Screencast

There is a lot of content so I recommend just git checkout GroupPage && git pull then cd frontend && npm run dev and also cd backend && npm run dev. If multiple people want me to add screenshots I can do that though 

Note: I added everyone as a reviewer for this because I feel like it's pretty key for the whole application so it should probably be reviewed more heavily than just a single component or something

### CODE REVIEW

**Review by palldas — CHANGES_REQUESTED** [review]
woah looks super good omg, some tiny frontend things:
- i like the ui for hovering a group a lot
- can you make it so the navbar is rendered on top always 
Screen Shot 2024-05-19 at 5 48 21 PM
Screen Shot 2024-05-19 at 5 52 02 PM 

- we might need to make the size of the group boxes smaller so we can fit the navigating buttons without being overlapped

- also search bar logic hasn't been implemented yet right?


everything else looks super good to me!

**Comment by jhcsdev** [comment]
@palldas for the first point thats an oops, when i was originally trying to do corners for the groups i messed around with the z-indices of stuff so that's why that's bugged I'll do that one rq
2) we def should do that but I'm not sure how to do that because its different for all screens and i tried fixing it by using percents for the w/h but that didn't work, it renders correctly on my side so its def something with different screen sizes. I'll try to figure that out but i might need help on that lol
3) search bar logic is actually implemented in frontend partially, but the rest API endpoint isn't set up on backend so it never retrieves data and therefore never renders anything new

**Comment by SilveerDusk** [comment]
@jhagendoornCP I think this looks really good but we got to resolve the merge conflicts before we can merge this in.

**Comment by jhcsdev** [comment]
Sg. @palldas do you mind if we delay fixing that UI issue until later? There's a good number of changes that I just want to have pushed to main to use in other branches

**Comment by jhcsdev** [comment]
To professor Zielke: We resolved these conflicts effectively together, which is why there is a lack of comments. We spent a good amount of time working on it and the failing check is because of an unfinished part of the project.

**Pull request merged**
