### PR TITLE
RemoveItem, basket UI owner views, assorted changes

### LINKED ISSUE #104: Edit Item Page to Match Groups Page UI
Change the header of the items page to look the same as the group page

### PR DESCRIPTION
**Pull request by jhcsdev**
The ultimate Smörgåsbord of so many different features, I got my fingers into so many of these project files!!! I cannot wait to fix all these merge conflicts!!!!!!!!!! 

### Including 
1. Updated items page colors to match theme of MyGroups page 
2. Updated items page header to match that of MyGroups page 
3. New backend route /baskets/:bid/removeitem which removes the metadata of an item supplied in body by basket id
4. New frontend lib in deletes, which calls above endpoint then deletes item if that was successful 
5. individual group page formatting fixes (padding on bottom of page, scrolls on basket, overflow on baskets, max height of basket shrunk and hardset, might need to be responsively expanded for smaller devices)
6. Removed edit group options from UI except visible to owner of group 
7. Removed add item, edit basket, add user to group options for all members of a group except those in basket 
8. Changed basketItem display, removed quantity, added "more info" button, added delete button 
9. Disabled edit item functionality unless member of basket 
10. Deprecated compact group 
11. Avatars on MyGroups page now render by username of members, owner of group displayed in largest avatar
12. Cleaned up old routes on app.tsx
13. Centered add group button 
14. RemoveUserFromGroup button/popover added, functionality not added since I almost had it but then all my changes were overwritten
15. Partial frontend "edit" route that doesn't have any functionality on backend (backend route got overwritten but frontend route survived somehow)

A lot of this should have been built on its own branch rather than grouping everything into one huge merge, I just didn't expect to be working on so much stuff and before I knew it I had everything piled into one branch, that's mb. I think there were other small changes that I made but nothing app-breaking.. I believe

It says I edited a lot of files but that's only because I merged from main to get the most updated state of userAuth 

UI Features that were added in this branch but that do NOT yet have functionality included: 
1. Search bar on single group page 
2. RemoveUsers button

Note: Last commit message is RemoveUser, should be RemoveItem I'm just braindead after redoing everything that I built last night 

### Testing
Extensive boomerang testing done on removeitem from basket group, UI changes had visible testing

### CODE REVIEW

**Comment by zmattes04** [comment]
can you make it pass the tests or nah

**Comment by jhcsdev** [comment]
> can you make it pass the tests or nah


Yeye I'm working on that rn its just cuz there's a couple things missing on imports/stuff it'll be good in 5 min

**Comment by SilveerDusk** [comment]
@jhagendoornCP can you share a couple screenshots of the new UI/other changes if possible?

**Comment by jhcsdev** [comment]
> @jhagendoornCP can you share a couple screenshots of the new UI/other changes if possible?

ye
Screenshot 2024-06-02 at 8 37 54 PM
Not member of basket: (also note that for baskets with 1 member, an avatar of the member is rendered)
Screenshot 2024-06-02 at 8 38 13 PM
Member of basket
Screenshot 2024-06-02 at 8 38 38 PM
Not group owner: 
Screenshot 2024-06-02 at 8 39 11 PM
Group owner: 
Screenshot 2024-06-02 at 8 39 27 PM
Items page: 
Screenshot 2024-06-02 at 8 39 55 PM
Padding on bottom of box
Screenshot 2024-06-02 at 8 43 56 PM

**Review by SilveerDusk — CHANGES_REQUESTED** [review]
For some reason the branch is behind );
Will approve once branch is updated and merge conflicts are solved. 
Also the avatars are not loading on the groups page for me, but I will update you once the merge conflicts are solved cause it might be that.

**Comment by jhcsdev** [comment]
> For some reason the branch is behind ); Will approve once branch is updated and merge conflicts are solved. Also the avatars are not loading on the groups page for me, but I will update you once the merge conflicts are solved cause it might be that.

That's weird that it's showing up as merge conflicts for you because it's not showing merge conflicts for me locally or here on github so I'd appreciate if you could fix any errors that you're seeing

**Comment by SilveerDusk** [comment]
Pulled the changes and then it was working just fine lol, guess i was just behind one or two commits!

**Review by SilveerDusk — APPROVED** [review]
Fantastic work!

**Comment by sofijadimitrijevic1** [comment]
This looks awesome, I'll work on changing the individual groups page header once you merge otherwise great job!!

**Comment by jhcsdev** [comment]
thanks guys i'm gonna go ahead and merge!

**Pull request merged**
