### PR TITLE
Created cypress component tests

### PR DESCRIPTION
**Pull request by jhcsdev**
Developed component tests with cypress testing 

1. Page selector 
2. Skeleton group 
3. Search bar 
4. constrained text

Developed these a week ago, left branch open and didn't make pull request because I though more component tests would be made but we decided to stop making component tests and focus on one big E2E test instead. 

Files changed: 

1. 4 cypress component tests 
2. cypress config 
3. constrained text 
4. compact group 
5. page selector & page selector buttons
6. search bar 
7. skeleton group 
8. myGroups page

Note to reviewer: Please review changes in MyGroups page carefully to ensure nothing is broken, I did my best resolving merge conflicts but always good to get a second pair of eyes

### CODE REVIEW

**Review by SilveerDusk — APPROVED** [review]
Looks good! More tests the merrier!

**Comment by sofijadimitrijevic1** [comment]
big e2e test coming up!

**Comment by zmattes04** [comment]
Good work fix merge conflicts and your good to go! You are a rockstar ! You deserve a star!!!

**Comment by palldas** [comment]
it's amazing what this has done for society! keep up the great work!

**Comment by jhcsdev** [comment]
Wow, everyone. These comments are making me cry tears of joy. I'm so happy that we have such a great community here. Thank you everyone.

**Pull request merged**
